config/routes.rb
QuickPlanOCCI::Application.routes.draw do  
  resources :meetings
  resources :people
  
  match 'meetings/new' => 'meetings#new', :via => [:get, :post]
  match 'meetings/:id/edit' => 'meetings#edit', :via => [:get, :put]
  match 'manage/:id' => 'meetings#edit'
  match 'rsvp/:id/:option' => 'people#edit'

  root :to => 'meetings#new'

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base

  attr_accessor :send_to_me

  has_one :creator, :class_name => "Person", :dependent => :destroy
  has_many :topics, :class_name => "Topic", :dependent => :destroy
  has_many :participants, :class_name => "Person", :dependent => :destroy
  accepts_nested_attributes_for :creator, :allow_destroy => true
  accepts_nested_attributes_for :topics, :allow_destroy => true
  accepts_nested_attributes_for :participants, :allow_destroy => true

  validates_presence_of :subject, :date
end

app/models/meeting/task.rb
class MeetingTask < ActiveRecord::Base
  belongs_to :topic
end

app/models/meeting/topic.rb
class Meeting::Topic < ActiveRecord::Base
  belongs_to :meeting
  has_many :tasks, :dependent => :destroy
  accepts_nested_attributes_for :tasks, :allow_destroy => true, :reject_if => proc { |attributes| attributes['description'].blank? }
end

app/models/meeting/topic/task.rb
class Meeting::Topic::Task < ActiveRecord::Base
  belongs_to :topic
  belongs_to :assignee, :class_name => "Person"

  set_table_name "meeting_tasks"
end

app/controllers/meetings/tasks_controller.rb
class MeetingTasksController < ApplicationController
  # GET /meeting_tasks
  # GET /meeting_tasks.json
  def index
    @meeting_tasks = MeetingTask.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meeting_tasks }
    end
  end

  # GET /meeting_tasks/1
  # GET /meeting_tasks/1.json
  def show
    @meeting_task = MeetingTask.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meeting_task }
    end
  end

  # GET /meeting_tasks/new
  # GET /meeting_tasks/new.json
  def new
    @meeting_task = MeetingTask.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meeting_task }
    end
  end

  # GET /meeting_tasks/1/edit
  def edit
    @meeting_task = MeetingTask.find(params[:id])
  end

  # POST /meeting_tasks
  # POST /meeting_tasks.json
  def create
    @meeting_task = MeetingTask.new(params[:meeting_task])

    respond_to do |format|
      if @meeting_task.save
        format.html { redirect_to @meeting_task, notice: 'Meeting task was successfully created.' }
        format.json { render json: @meeting_task, status: :created, location: @meeting_task }
      else
        format.html { render action: "new" }
        format.json { render json: @meeting_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meeting_tasks/1
  # PUT /meeting_tasks/1.json
  def update
    @meeting_task = MeetingTask.find(params[:id])

    respond_to do |format|
      if @meeting_task.update_attributes(params[:meeting_task])
        format.html { redirect_to @meeting_task, notice: 'Meeting task was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @meeting_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meeting_tasks/1
  # DELETE /meeting_tasks/1.json
  def destroy
    @meeting_task = MeetingTask.find(params[:id])
    @meeting_task.destroy

    respond_to do |format|
      format.html { redirect_to meeting_tasks_url }
      format.json { head :ok }
    end
  end
end

app/controllers/meetings/topics_controller.rb
class MeetingTopicsController < ApplicationController
  # GET /meeting_topics
  # GET /meeting_topics.json
  def index
    @meeting_topics = MeetingTopic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meeting_topics }
    end
  end

  # GET /meeting_topics/1
  # GET /meeting_topics/1.json
  def show
    @meeting_topic = MeetingTopic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meeting_topic }
    end
  end

  # GET /meeting_topics/new
  # GET /meeting_topics/new.json
  def new
    @meeting_topic = MeetingTopic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meeting_topic }
    end
  end

  # GET /meeting_topics/1/edit
  def edit
    @meeting_topic = MeetingTopic.find(params[:id])
  end

  # POST /meeting_topics
  # POST /meeting_topics.json
  def create
    @meeting_topic = MeetingTopic.new(params[:meeting_topic])

    respond_to do |format|
      if @meeting_topic.save
        format.html { redirect_to @meeting_topic, notice: 'Meeting topic was successfully created.' }
        format.json { render json: @meeting_topic, status: :created, location: @meeting_topic }
      else
        format.html { render action: "new" }
        format.json { render json: @meeting_topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meeting_topics/1
  # PUT /meeting_topics/1.json
  def update
    @meeting_topic = MeetingTopic.find(params[:id])

    respond_to do |format|
      if @meeting_topic.update_attributes(params[:meeting_topic])
        format.html { redirect_to @meeting_topic, notice: 'Meeting topic was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @meeting_topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meeting_topics/1
  # DELETE /meeting_topics/1.json
  def destroy
    @meeting_topic = MeetingTopic.find(params[:id])
    @meeting_topic.destroy

    respond_to do |format|
      format.html { redirect_to meeting_topics_url }
      format.json { head :ok }
    end
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  # GET /meetings
  # GET /meetings.json

  def odt(meeting)
    report = ODFReport::Report.new("#{Rails.root}/app/test.odt") do |r|
      
      r.add_field "SUBJECT",  meeting.subject
      r.add_field "DATE", meeting.date.to_s
      r.add_field "HOSTED_BY", Person.find(meeting.creator_id).name
      attendances = []
      meeting.participants.each do |participant|
        if participant.presence == "yes"
          attendances << participant.name        
        end
      end
      r.add_field "ATTENDANCES", attendances.join(", ")
      tasks = "\n"
      meeting.topics.each do |topic|
        if topic.description
          tasks += topic.name+":\n"+topic.description+"\n"
          topic.tasks.each do |task|
            tasks += Person.find(task.person_id).name+": "+task.description+"\n"
          end
          tasks += "\n"
        end
      end
      r.add_field "TOPICS_AND_TASKS", tasks
    end

    report_file_name = report.generate
    return report_file_name  
  end

  def index
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/new
  # GET /meetings/new.json
  def new
    @meeting = Meeting.new(params[:meeting])
    @meeting.creator = Person.new unless @meeting.creator
    
    if(params[:step] != 'first' and params[:step] != 'details')    
      @step = 'first'
    else
      @step = params[:step]
    end 
  
    @meeting.build_creator
    topic = @meeting.topics.build
    
    respond_to do |format|
      format.html
      format.js
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/1/edit
  def edit
    @meeting = Meeting.find_by_management_url!(params[:id])
    
    @gcal = export_cal(@meeting)

    @meeting.topics.each do |topic|
      topic.tasks.build
    end

    if(@meeting.state == 'A' or @meeting.state == 'B')    
      @step = 'invites'
    elsif(@meeting.state == nil)
      @step = 'details'  
    else
      @step = 'meeting'
    end

    puts @step

    if(params[:commit] == "Go back")
      @step = 'details_edit'
    end

    respond_to do |format|
      format.html
      format.js
      format.json { render json: @meeting }
    end
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(params[:meeting])
    @creator = Person.new(params[:meeting][:creator_attributes])
    @creator.save
    @meeting.creator_id = @creator.id
    begin
      @meeting.date = (DateTime.strptime(params[:meeting][:date], '%m/%d/%Y %H:%M ')).to_datetime
    rescue Exception=>e
      @meeting.date = nil
    end
    @meeting.state = 'A'
    respond_to do |format|
      if @meeting.save
        @meeting.topics.each do |topic|
          if topic.name == nil or topic.name.size == 0
            @meeting.topics.delete(topic)
          end
        end
        flash[:notice] = "An email was sent to you with the meeting management. If you want, you can use the following tool to easily invite them:"
        @meeting.management_url = SecureRandom.base64(8).gsub("/","_").gsub(/=+$/,"")+@meeting.id.to_s
        @meeting.participants = []        
        @meeting.save
        url = (Rails.env.development?) ? "http://localhost:3000/manage/" : "http://quickplan.heroku.com/manage/"
        url = url + @meeting.management_url
        begin
          Notifier.management_email(@meeting, url).deliver
        rescue Exception=>e    
        end        
        format.html { redirect_to edit_meeting_path(:id => @meeting.management_url, :step => "invites")}
        format.js   { redirect_to edit_meeting_path(:id => @meeting.management_url, :step => "invites")}
        format.json { render json: @meeting, status: :created, location: @meeting }
      else
        format.html { render action: :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meetings/1
  # PUT /meetings/1.json
  def update
    @meeting = Meeting.find_by_management_url(params[:id])
    
    if(params[:commit] == "Continue")
      @step = 'invites'
    elsif(params[:commit] == "Go back")
      @step = 'details_edit'
    elsif(params[:commit] == "Meeting Management")
      @step = 'management'
    elsif(params[:commit] == "Start Meeting")
      @meeting.state = 'C'
      @step = 'meeting'
      @meeting.save
    elsif(params[:commit] == "Generate Documentation")
      @step = 'meeting'
    elsif(params[:commit] == "Invite")
      @meeting.state = 'B'
      emails = params[:meeting][:mail_list].split(',')  
      participants = []
      emails.each do |email|
        email = email.gsub("\"","")
        if email =~ /[^"]*[ ]*<[^"]*@[^"]*.[^"]*>/
          participant = Person.new(:name => email.scan(/([^"]*)</)[0][0].strip, :email => email.scan(/<([^"]*)>/)[0][0].strip, :invitation_url => SecureRandom.base64(8).gsub("/","_").gsub(/=+$/,"")+participants.length.to_s)
          participants << participant
        elsif email =~ /<[^"]*@[^"]*.[^"]*>/
          participant = Person.new(:name => 'Participant name', :email => email.scan(/<([^"]*)>/)[0][0].strip, :invitation_url => SecureRandom.base64(8).gsub("/","_").gsub(/=+$/,"")+participants.length.to_s)
          participants << participant
        elsif email =~ /[^"]*@[^"]*.[^"]*/
          participant = Person.new(:name => "Participant name", :email => email.scan(/([^"]*)/)[0][0].strip, :invitation_url => SecureRandom.base64(8).gsub("/","_").gsub(/=+$/,"")+participants.length.to_s) 
          participants << participant
        end
      end
      if participants.length != 0
        @meeting.participants |= participants
      end
      params[:meeting][:mail_list] = ""
      @meeting.save
      @step = 'invites'
    elsif(params[:commit] == "Invite more participants")
      @step = 'invites'
    end
  
    respond_to do |format|     
      if @meeting.update_attributes(params[:meeting])
        if(params[:commit] == "Invite")
          participants.each do |participant|
            begin
              Notifier.invitation_email(participant, @meeting).deliver     
            rescue Exception=>e
            end          
          end        
        elsif(params[:commit] == "Generate Documentation")
          @meeting.participants.each do |participant|
            begin            
              Notifier.report_email(participant, @meeting, odt(@meeting)).deliver     
            rescue Exception=>e
            end          
          end
          begin
            Notifier.report_email(Person.find(@meeting.creator_id), @meeting, odt(@meeting)).deliver 
          rescue Exception=>e
          end        
        end
        format.html { redirect_to edit_meeting_path(:id => @meeting.management_url, :step => @step)}
        format.js   { redirect_to edit_meeting_path(:id => @meeting.management_url, :step => @step)}
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to meetings_url }
      format.json { head :ok }
    end
  end
end

app/helpers/meetings/people_helper.rb
module Meetings::PeopleHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
  def default_invitation_text(meeting)
    url = (Rails.env.development?) ? "http://localhost:3000/" : "http://localhost:3000/"
    url = url + meeting.management_url      
    return "Hi,
 I am using QuickPlan to notify you of a new meeting called '#{meeting.subject}', due to #{meeting.date.to_s}.

Regards,
#{meeting.creator.name}"
  end
end

app/views/meetings/_export_cal.html.haml
%p.green-button
  Export meeting to:
  %br
  %a{:href => "http://www.google.com/calendar/event?action=TEMPLATE&text=#{@gcal[:text]}&dates=#{@gcal[:dates]}&details=#{@gcal[:details]}", :target => "_blank", :class => "round"} Google Calendar

app/views/meetings/_first_step.html.haml
- app_title "New Meeting"

#step
  %p
    ="QuickPlan is the easiest way to plan and manage your meetings. Ready to use, completely free and no signup required!"
  %p{:class=> "big-button"}
    = link_to "Create new meeting", new_meeting_path(:step => "details"),  :class => "round"

app/views/meetings/_form_attendances.html.haml
- if @meeting.errors.any?
  #errorExplanation
    %h2= "#{pluralize(@meeting.errors.count, 'error')} prohibited this user from being saved:"
    %ul
    - @meeting.errors.full_messages.each do |msg|
      %li= msg

- count = 0

%table{:id => "stripe", :style => "width: 510px; margin: 0 auto 0 auto"}
  = f.fields_for :participants  do |p|   
    %tr    
      %td{:style => "text-align: left"}
        %b
          = @meeting.participants.all[count].name
        %i
          = "(#{@meeting.participants.all[count].email})"
      %td
        - temp = ((@meeting.participants.all[count].presence ? @meeting.participants.all[count].presence : @meeting.participants.all[count].rsvp) == 'yes')
        = p.radio_button(:presence, "yes", :checked => temp)
      %td
        = p.radio_button(:presence, "no", :checked => !temp)
    - count+=1

:javascript

$(function() {
  var table = document.getElementById("stripe");
  var rows = table.getElementsByTagName("tr");
  for(i = 0; i < rows.length; i++){
    if(i % 2 == 0)
      rows[i].className = "even";
    else
      rows[i].className = "odd";
  }
});
$(function() {
    $('input:radio[value="yes"]').each(function() {
        if ( this.checked==true )
          $('<a class="radio-fx-yes" href="#"><div class="radio-checked-yes"></div></a>').insertAfter(this);
        else
          $('<a class="radio-fx-yes" href="#"><div class="radio-yes"></div></a>').insertAfter(this);
        $(this).hide();
    });
    $('.radio-fx-yes').live('click',function(e) {
        e.preventDefault();
          var $check = $(this).prev('input');
          $(this).find('div').attr('class','radio-checked-yes');          
          $check.attr('checked', true);
          $('.radio-fx-no div').each(function() {
              var $par = $(this).parent().prev('input').get(0);
              if ( $par.checked==false ) $(this).parent().find('div').attr('class','radio-no'); 
          });
    });
});
$(function() {
    $('input:radio[value="no"]').each(function() {
        if ( this.checked==true )
          $('<a class="radio-fx-no" href="#"><div class="radio-checked-no"></div></a>').insertAfter(this);
        else
          $('<a class="radio-fx-no" href="#"><div class="radio-no"></div></a>').insertAfter(this);
        $(this).hide();
    });
    $('.radio-fx-no').live('click',function(e) {
        e.preventDefault();
          var $check = $(this).prev('input');
          $(this).find('div').attr('class','radio-checked-no');          
          $check.attr('checked', true);
          $('.radio-fx-yes div').each(function() {
              var $par = $(this).parent().prev('input').get(0);
              if ( $par.checked==false ) $(this).parent().find('div').attr('class','radio-yes'); 
          });
    });
});

app/views/meetings/_form_invites.html.haml
- if @meeting.errors.any?
  #errorExplanation
    %h2= "#{pluralize(@meeting.errors.count, 'error')} prohibited this user from being saved:"
    %ul
    - @meeting.errors.full_messages.each do |msg|
      %li= msg

.field
  %p
    = f.label :mail_list, "Participants emails (separated by commas)"
    %br
    = f.text_area :mail_list
    %p{:class => 'small-button'}    
      = submit_tag 'Invite', :class => 'smallround'

app/views/meetings/_form_management.html.haml
- if @meeting.errors.any?
  #errorExplanation
    %h2= "#{pluralize(@meeting.errors.count, 'error')} prohibited this user from being saved:"
    %ul
    - @meeting.errors.full_messages.each do |msg|
      %li= msg

- count = 0

%table{:id => "stripe", :style => "width: 510px; margin: 0 auto 0 auto; text-align: left"}
  = f.fields_for :participants  do |p|
    %tr    
      %td
        - if @meeting.participants.all[count].rsvp == 'yes'
          - rsvp = image_tag("g_tick.png", :style => "margin-bottom:-8px")
        - elsif @meeting.participants.all[count].rsvp == 'no'
          - rsvp = image_tag("r_delete.png", :style => "margin-bottom:-8px")
        - else
          - rsvp = image_tag("w_faq.png", :style => "margin-bottom:-8px")
        = p.label :rsvp, rsvp
        = p.text_field :name, :style => "width: 200px", :value => (@meeting.participants.all[count].name ? @meeting.participants.all[count].name : 'Participant name'), :onfocus => '(this.value == "Participant name") ? this.value = "" : this.value'
        %i
          = "(#{@meeting.participants.all[count].email})"
    - count+=1

:javascript
  if(document.getElementsByTagName){
    var table = document.getElementById("stripe");
    var rows = table.getElementsByTagName("tr");
    for(i = 0; i < rows.length; i++){
      if(i % 2 == 0) rows[i].className = "even";
      else rows[i].className = "odd";
    }
  }

app/views/meetings/_form_record.html.haml
- if @meeting.errors.any?
  #errorExplanation
    %h2= "#{pluralize(@meeting.errors.count, 'error')} prohibited this user from being saved:"
    %ul
    - @meeting.errors.full_messages.each do |msg|
      %li= msg

- count = 0

%div{:style => "width: 510px; margin: 0 auto 0 auto"}
  - count = 0
  - @meeting.topics.each do |topic|
    = f.fields_for :topics, topic  do |p|   
      .field
        %p{:class => 'fields'}
          = p.label :name, @meeting.topics.all[count].name
          %br
          = p.text_area :description, :class => 'topic'
        - count += 1
        - topic.tasks.each.with_index do |task,index|
          = p.fields_for :tasks, task do |t|
            = render "task_fields", :f => t
        %p{:style => "display: none"} 
          = link_to_add_fields "add", p, :tasks
        %p
          %br

:javascript

$(function() {
  $('.last').each(function() {
    if ($(this).val() != "") {
      $(this).attr('class','inputlist');
      $(this).next('span').show();
    }
  });
  $('.last').live('click keyup',function(e) {
    if ($(this).val() != "") {
      $(this).attr('class','inputlist');
      $(this).next('span').show();
      $(this).parent().parent().parent().find('.hidden_button').click();
    }
  });
});

app/views/meetings/_invites_step.html.haml
- app_title "Meeting Management"

#step
  %h3="Meeting Management"
  
  .form
    = form_for @meeting, :as => :meeting, :url => {:controller => :meetings, :action => :update},  do |f|
      - if flash[:notice]
        %p
          .notice
            = flash[:notice]      
      = render "form_invites", :f => f     

  .form
    = form_for @meeting, :url => {:controller => :meetings, :action => :update} , :html => {:class => 'participants'}  do |f|
      = render "form_management", :f => f
      %p{:class => 'big-button'}
        - if @meeting.participants.length == 0  
          = submit_tag 'Start Meeting', :class => 'round disabled', :disabled => true
        - else
          = submit_tag 'Start Meeting', :class => 'round'
- content_for :export_cal, render(:partial => 'export_cal')

app/views/meetings/_management_step.html.haml
- app_title "Invite participants"

#step
  %h3="Meeting management"
  .form
    = form_for @meeting, :url => {:controller => :meetings, :action => :update}   do |f|
      = render "form_management", :f => f
      %p{:class => 'big-button'}
        = submit_tag 'Start Meeting', :class => 'round'
- content_for :export_cal, render(:partial => 'export_cal')

app/views/meetings/_meeting_step.html.haml
- app_title "#{@meeting.subject}"

#tabsdiv{:class=>"topround"}
  %ul{:id=>"tabs"}
    %li{:id=>"tab1", :class=>"topround", :onclick=> "showAttendances();"}
      ="Attendances"
    %li{:id=>"tab2", :class=>"topround", :onclick=> "showRecord();"}
      ="Record"

.form
  = form_for @meeting, :url => {:controller => :meetings, :action => :update}, :html => {:class => 'participants'}  do |f|

    #attendances
      = render "form_attendances", :f => f

    #record
      = render "form_record", :f => f

    %p{:class => 'big-button'}
      = submit_tag 'Save', :class => 'round'
      = submit_tag 'Generate Documentation', :class => 'round'

:javascript

$(document).ready(function() {
  showAttendances();
});

app/views/meetings/_task_fields.html.haml
.field
  %p{:class => 'fields', :style => "margin: 0"}
    - temp = [Person.find(@meeting.creator_id)]
    - temp |= @meeting.participants
    = f.select :person_id, temp.collect {|p| [ p.name, p.id ] }
    = f.text_field :description, :class => "inputlist last", :onblur => "if ($(this).val() == \"\" && !$(this).hasClass('last')) $(this).parent().find('.remove').click();"
    %span{:style => "display: none"}
      = link_to_remove_fields image_tag("w_delete.png", :style => "margin-bottom: -10px"), f

app/views/meetings/_topic_fields.html.haml
.field
  %p{:class => 'fields'}
    = f.text_field :name, :class => "inputlist last"
    %span{:style => "display: none"}
      = link_to_remove_fields image_tag("w_delete.png", :style => "margin-bottom: -9px"), f

app/views/meetings/index.html.haml
%h1= t('.title')
%p= link_to t('.new_meeting'), new_meeting_path

%table
  %thead
    %tr
      %th= Meeting.human_attribute_name :id
      %th= Meeting.human_attribute_name :creator_id
      %th= Meeting.human_attribute_name :date
      %th= Meeting.human_attribute_name :state
      %th= Meeting.human_attribute_name :deleted_at
      %th{:colspan => 3}= t 'actions'
  
  %tbody
    - for meeting in @meetings
      %tr{ :class => cycle(:odd, :even) }
        %td= meeting.id
        %td= meeting.creator_id
        %td= meeting.date
        %td= meeting.state
        %td= meeting.deleted_at
        %td.action= link_to t('show'), meeting
        %td.action= link_to t('edit'), edit_meeting_path(meeting)
        %td.action= link_to t('destroy'), meeting, :confirm => t('are_you_sure'), :method => :delete

app/views/meetings/new.js.erb
alert("aaaa")
$('#step').html("<%=escape_javascript(render "#{@step}_step")%>");

app/views/meetings/show.html.haml
%h1= t '.title'
%p
  = link_to t('back'), meetings_path
  = link_to t('edit'), edit_meeting_path(@meeting)

%dl
  %dt= Meeting.human_attribute_name :id
  %dd= @meeting.id
  %dt= Meeting.human_attribute_name :creator_id
  %dd= @meeting.creator_id
  %dt= Meeting.human_attribute_name :date
  %dd= @meeting.date
  %dt= Meeting.human_attribute_name :state
  %dd= @meeting.state
  %dt= Meeting.human_attribute_name :deleted_at
  %dd= @meeting.deleted_at