config/routes.rb
QuickPlanOCCI::Application.routes.draw do  
  resources :meetings
  resources :people
  
  match 'meetings/new' => 'meetings#new', :via => [:get, :post]
  match 'meetings/:id/edit' => 'meetings#edit', :via => [:get, :put]
  match 'manage/:id' => 'meetings#edit'
  match 'rsvp/:id/:option' => 'people#edit'

  root :to => 'meetings#new'

end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :meeting
  has_many :tasks
  
  set_table_name "meeting_people"

  validates_presence_of :name  
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def edit
    @person = Person.find_by_invitation_url!(params[:id])
    @person.rsvp = params[:option]
    @step = params[:step] ? params[:step] : 'form' 
    
    @gcal = export_cal(@person.meeting)

    respond_to do |format|
      format.html
      format.js
      format.json { render json: @meeting }
    end
  end

  def update
    @person = Person.find_by_invitation_url(params[:id])
    @step = "confirmation"
    
    @gcal = export_cal(@person.meeting)

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to edit_person_path(:id => @person.invitation_url, :step => @step)}
        format.js   { redirect_to edit_person_path(:id => @person.invitation_url, :step => @step)}
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/meetings/people_helper.rb
module Meetings::PeopleHelper
end

app/views/people/_confirmation_step.haml
- app_title "New Meeting"

#step
  %h3
    Thank you!
  %p
    ="Thank you for RSVPing"

app/views/people/_export_cal.html.haml
%p.green-button
  Export meeting to:
  %br
  %a{:href => "http://www.google.com/calendar/event?action=TEMPLATE&text=#{@gcal[:text]}&dates=#{@gcal[:dates]}&details=#{@gcal[:details]}", :target => "_blank", :class => "round"} Google Calendar

app/views/people/_form.html.haml
.field
= f.label :name, "Please confirm your name:"
%br
= f.text_field :name
= f.hidden_field :rsvp

app/views/people/_form_step.html.haml
- app_title "Confirmation sent"

#step
  %h3="Thank you for your confirmation!"
  .form
    = form_for @person, :url => {:controller => :people, :action => :update} ,:remote => true  do |f|
      = render "form", :f => f
      %p{:class => 'big-button'}
        = submit_tag 'Confirm', :class => 'round'
- content_for :export_cal, render(:partial => 'export_cal')

app/views/people/edit.html.haml
= render :partial => "#{@step}_step"

app/views/people/edit.js.erb
$('#step').html("<%=escape_javascript(render "#{@step}_step")%>");

app/views/people/index.html.haml
%h1= t('.title')
%p= link_to t('.new_meeting_person'), new_meeting_person_path

%table
  %thead
    %tr
      %th= MeetingPerson.human_attribute_name :id
      %th= MeetingPerson.human_attribute_name :name
      %th= MeetingPerson.human_attribute_name :email
      %th= MeetingPerson.human_attribute_name :rsvp
      %th= MeetingPerson.human_attribute_name :presence
      %th= MeetingPerson.human_attribute_name :meeting_id
      %th= MeetingPerson.human_attribute_name :deleted_at
      %th{:colspan => 3}= t 'actions'
  
  %tbody
    - for meeting_person in @meeting_people
      %tr{ :class => cycle(:odd, :even) }
        %td= meeting_person.id
        %td= meeting_person.name
        %td= meeting_person.email
        %td= meeting_person.rsvp
        %td= meeting_person.presence
        %td= meeting_person.meeting_id
        %td= meeting_person.deleted_at
        %td.action= link_to t('show'), meeting_person
        %td.action= link_to t('edit'), edit_meeting_person_path(meeting_person)
        %td.action= link_to t('destroy'), meeting_person, :confirm => t('are_you_sure'), :method => :delete

app/views/people/new.html.haml
%h1= t '.title'
%p= link_to t('back'), meeting_people_path
= render 'form'

app/views/people/show.html.haml
%h1= t '.title'
%p
  = link_to t('back'), meeting_people_path
  = link_to t('edit'), edit_meeting_person_path(@meeting_person)

%dl
  %dt= MeetingPerson.human_attribute_name :id
  %dd= @meeting_person.id
  %dt= MeetingPerson.human_attribute_name :name
  %dd= @meeting_person.name
  %dt= MeetingPerson.human_attribute_name :email
  %dd= @meeting_person.email
  %dt= MeetingPerson.human_attribute_name :rsvp
  %dd= @meeting_person.rsvp
  %dt= MeetingPerson.human_attribute_name :presence
  %dd= @meeting_person.presence
  %dt= MeetingPerson.human_attribute_name :meeting_id
  %dd= @meeting_person.meeting_id
  %dt= MeetingPerson.human_attribute_name :deleted_at
  %dd= @meeting_person.deleted_at